"""
Nginx config generation and reload utility.

Writes per-domain server blocks to NGINX_DOMAINS_DIR and reloads nginx
via docker exec through the mounted Docker socket.
"""
import asyncio
import os

NGINX_DOMAINS_DIR = os.getenv("NGINX_DOMAINS_DIR", "/etc/nginx/conf.d/domains")
COMPOSE_PROJECT_NAME = os.getenv("COMPOSE_PROJECT_NAME", "linkspanel")

_NGINX_CONTAINER = f"{COMPOSE_PROJECT_NAME}-nginx-1"

_SERVER_BLOCK_TEMPLATE = """\
# Auto-generated by linkspanel bot — do not edit manually
server {{
    listen 443 ssl http2;
    server_name {domain} *.{domain};

    ssl_certificate     /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location /static/ {{
        alias /app/static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }}

    location /chat/stream/ {{
        proxy_pass         http://api:8000;
        proxy_set_header   X-Forwarded-Host $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header   Host             $host;
        proxy_set_header   Connection       '';
        proxy_http_version 1.1;
        proxy_read_timeout 3600s;
        proxy_buffering    off;
        proxy_cache        off;
        chunked_transfer_encoding on;
    }}

    location / {{
        proxy_pass         http://api:8000;
        proxy_set_header   X-Forwarded-Host $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header   Host             $host;
        proxy_read_timeout 10s;
    }}
}}
"""


def write_domain_conf(domain: str) -> None:
    """Write an nginx server block for *domain* into NGINX_DOMAINS_DIR."""
    os.makedirs(NGINX_DOMAINS_DIR, exist_ok=True)
    conf_path = os.path.join(NGINX_DOMAINS_DIR, f"{domain}.conf")
    with open(conf_path, "w", encoding="utf-8") as f:
        f.write(_SERVER_BLOCK_TEMPLATE.format(domain=domain))


async def reload_nginx() -> tuple[bool, str]:
    """
    Send 'nginx -s reload' inside the nginx container via docker exec.

    Returns (True, "") on success, or (False, error_message) on failure.
    """
    cmd = ["docker", "exec", _NGINX_CONTAINER, "nginx", "-s", "reload"]
    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )
        try:
            stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=15)
        except asyncio.TimeoutError:
            proc.kill()
            await proc.communicate()
            return False, "nginx reload завис (таймаут 15с)."

        output = stdout.decode(errors="replace").strip() if stdout else ""

        if proc.returncode == 0:
            return True, ""

        return False, f"nginx reload завершился с ошибкой:\n<code>{output or 'нет вывода'}</code>"

    except FileNotFoundError:
        return False, "docker не найден. Убедись что docker установлен на хосте."
    except Exception as e:
        return False, f"Ошибка выполнения docker exec: <code>{e}</code>"
